{% set name = "pyeosim" %}
{% set version = "0.2.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: .

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv "

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python>=3.7
    - xarray
    - pyyaml
    - scipy
    - numpy
    - dask
    - py6s
    - pandas
    - xlrd
    - netcdf4
    - matplotlib
